# -*- coding: utf-8 -*-
#
#  Copyright 2026 Ramil Nugmanov <nougmanoff@protonmail.com>
#  This file is part of chython.
#
#  chython is free software; you can redistribute it and/or modify
#  it under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Lesser General Public License for more details.
#
#  You should have received a copy of the GNU Lesser General Public License
#  along with this program; if not, see <https://www.gnu.org/licenses/>.
#
"""Freeze a corpus of arena version-4 buffers and the answers they must still give.

Run against a build whose `STRUCT_VERSION` is 4.  The output is committed; no later build writes
version-4 bytes, so this file cannot be regenerated.

    python -m chython.core.test.gen_v4_fixtures
"""
from gzip import open as gzip_open
from pathlib import Path
from pprint import pformat

from chython.core._core import read_smiles


# The generated file is source and carries the tree's header like any other; it cannot be regenerated
# by a later build, so the header is written here rather than added by hand afterwards.
HEADER = '''# -*- coding: utf-8 -*-
#
#  Copyright 2026 Ramil Nugmanov <nougmanoff@protonmail.com>
#  This file is part of chython.
#
#  chython is free software; you can redistribute it and/or modify
#  it under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Lesser General Public License for more details.
#
#  You should have received a copy of the GNU Lesser General Public License
#  along with this program; if not, see <https://www.gnu.org/licenses/>.
#
'''

# Public compounds, each carrying a stated parity of a different kind, plus two that carry none.
STRUCTURES = (
    'C[C@H](N)C(=O)O',                      # L-alanine, one tetrahedral centre
    'C/C=C/C',                              # trans-2-butene, one cis/trans unit
    'C/C=C\\C',                             # cis-2-butene
    'O[C@@H]1[C@H](O)[C@@H](O)[C@H](O)[C@H](O)[C@H]1O',   # myo-inositol, six centres
    'C[C@H](O)[C@@H](C)O',                  # two centres, one molecule
    'CC(=O)Oc1ccccc1C(=O)O',                # aspirin, no stereo
    'c1ccccc1',                             # benzene, no stereo
)


def _answers(mol):
    return {'parities': {n: mol.parity_of(n) for n in mol.atom_numbers if mol.parity_of(n)},
            'wedges': mol.wedges(),
            'stereo_groups': mol.stereo_groups()}


def _sgroup_and_stereo():
    """One record with S-groups AND a stereocentre.

    The only record that reaches the S-group and blob memcpy arms of the arena's segment carry; no
    molecule built from SMILES alone reaches those arms.  `set_sgroups` is the only constructor in
    the tree for this path.  Read `test_sgroups.py` for the record shape (`{'type': b'DAT',
    'name': b'...', 'atoms': (id, ...), 'data': [b'...'], 'index': 1}`).
    """
    mol = read_smiles('C[C@H](N)C(=O)O')
    ids = list(mol.atom_numbers)
    mol.set_sgroups([{'type': b'DAT', 'name': b'BATCH', 'atoms': (ids[1],),
                      'data': [b'lot-42'], 'index': 1}])
    return mol


def main():
    here = Path(__file__).parent
    records = []
    answers = {}
    sgroup_mol = _sgroup_and_stereo()
    for mol in [read_smiles(text) for text in STRUCTURES] + [sgroup_mol]:
        raw = mol.to_bytes()
        assert raw[4] == 4, 'this build writes arena version %d, not 4' % raw[4]
        records.append(raw)
        answers[str(mol)] = _answers(mol)
    sgroup_raw = records[-1]
    assert sgroup_mol.sgroups, 'the S-group record did not survive; check set_sgroups'
    with gzip_open(here / 'arena_v4_corpus.bin.gz', 'wb') as f:
        for raw in records:
            f.write(len(raw).to_bytes(4, 'little'))
            f.write(raw)
    with open(here / 'v4_fixtures.py', 'w') as f:
        f.write(HEADER)
        f.write('# FROZEN. Generated by gen_v4_fixtures.py against a build whose STRUCT_VERSION was 4.\n'
                '# Nothing regenerates this: a later build cannot write a version-4 buffer.\n'
                '\nV4_ANSWERS = ')
        f.write(pformat(answers, width=110))
        f.write('\n\n# The one record carrying S-groups and a stereocentre together.\nV4_SGROUP_STEREO_BYTES = ')
        f.write(repr(sgroup_raw))
        f.write('\n')


if __name__ == '__main__':
    main()
