# -*- coding: utf-8 -*-
#
#  Copyright 2026 Ramil Nugmanov <nougmanoff@protonmail.com>
#  This file is part of chython.
#
#  chython is free software; you can redistribute it and/or modify
#  it under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU Lesser General Public License for more details.
#
#  You should have received a copy of the GNU Lesser General Public License
#  along with this program; if not, see <https://www.gnu.org/licenses/>.
#
"""What a patch must do with a stereocentre it destroys -- stated as a test rather than as a plan.

WHAT THE MEASUREMENT IS OF.  chython 2's patcher (`chython/reactor/base.py`, the unmatched-atom loop)
decides whether to carry a tetrahedral parity forward by asking whether the atom was stereogenic in the
OLD structure, and then stamps the raw parity with no retranslation:

    if sa.stereo is not None:
        if n in structure.stereogenic_tetrahedrons:   # <- the OLD structure
            a._stereo = sa.stereo                     # <- raw, un-retranslated
        else:
            stereo_atoms.append(n)                    # <- the retranslating path

One line, two consequences.  The question is asked of the OLD graph, so an atom that was stereogenic
and is not carries a parity it cannot own.  And where it is still stereogenic the parity is copied
rather than retranslated, so it means something else the moment the patch changes the neighbour order --
which is what the `stereo_atoms` path below it is for.  Both are inputs to the specification here; see
`docs/superpowers/` for the full reading.

THE FIXTURE IS (R)-gamma-valerolactone, a public compound, and its achiral twin is the control.
Five shipped templates open its ring in a way that leaves the carbinol carbon with two hydrogens and
no heteroatom -- it stops being a stereocentre -- and every one of them raises.  The achiral twin
goes through all five, so the difference is the stereo label and nothing else.

WHERE chython 2 RUNS.  Every measurement below is chython 2's behaviour and none of it is the core's,
so the whole matrix is evaluated INSIDE an installed 2.24 through `oracle` and what crosses back is the
outcome per template.  This file imports no chython 2: run against a pinned wheel, the pin outlives the
source it describes, which is the only way it stays checkable.
"""
from functools import lru_cache

from pytest import mark

from . import oracle


# (R)-gamma-valerolactone and its achiral twin.  Public compounds.
CHIRAL = 'C[C@@H]1CCC(=O)O1'
ACHIRAL = 'CC1CCC(=O)O1'

# Every shipped single-molecule template measured raising on CHIRAL and not on ACHIRAL.  MEASURED,
# not relayed: the list is regenerated by iterating the rule tables, because a count quoted from a
# report is stale the moment a template is added.
AFFECTED = [('_transformations', 'ester_to_amide'),
            ('_transformations', 'ester_to_hydroxamic_acid'),
            ('_transformations', 'ester_to_hydrazide'),
            ('_transformations', 'ester_hydrolysis'),
            ('_reductions', 'ester_to_alcohol')]


ORACLE_SCRIPT = r'''
def reactor(module, rule_name):
    mod = __import__('chython.algorithms.groups.' + module, fromlist=['rules'])
    for entry in mod.rules:
        if entry[0] == rule_name:
            return entry[-1]
    raise AssertionError(module + ':' + rule_name + ' is gone; the fixture list needs regenerating')


def run(module, rule_name, smi):
    """Apply one template and FORCE THE PRODUCT TO BE READ.

    `str(rxn)` is not decoration.  The patcher writes the bad label and returns happily; the label is
    only discovered when something asks the product what its stereo means, which is what a writer, a
    canonicaliser and an equality test all do.  A test that only applied the template would pass
    against a corrupt product.
    """
    from chython import smiles
    return [str(rxn) for rxn in reactor(module, rule_name)(smiles(smi))]


out = {}
for module, rule_name in _payload['templates']:
    for label, smi in _payload['molecules'].items():
        try:
            out[module + ':' + rule_name + ':' + label] = ['ok', len(run(module, rule_name, smi))]
        except Exception as e:
            # the EXCEPTION TYPE crosses back, not the object: the assertions below are about which
            # failure chython 2 produces, and a name is the whole of what they need
            out[module + ':' + rule_name + ':' + label] = ['raised', type(e).__name__]
_emit(out)
'''


@lru_cache(maxsize=1)
def _verdicts():
    """`{'module:rule:label': ['ok', n] | ['raised', 'KeyError']}` -- the whole matrix, one subprocess.

    Cached, because it is ten template applications and the interpreter start-up dominates.
    """
    return oracle.ask(ORACLE_SCRIPT,
                      {'templates': AFFECTED, 'molecules': {'chiral': CHIRAL,
                                                            'achiral': ACHIRAL}})


def test_the_control_goes_through_every_affected_template():
    """The achiral twin, so that the failures below are about the stereo label and nothing else."""
    verdicts = _verdicts()
    for module, rule_name in AFFECTED:
        outcome, detail = verdicts[f'{module}:{rule_name}:achiral']
        assert outcome == 'ok', (module, rule_name, detail)
        assert detail > 0, (module, rule_name)


def test_the_chython_two_patcher_writes_a_parity_the_product_cannot_read():
    """V2'S MEASURED BEHAVIOUR, PINNED SO IT CANNOT BE FORGOTTEN OR QUIETLY TURNED INTO SOMETHING ELSE.

    The day a patcher stops raising here this test FAILS, which is the notification that the acceptance
    test below is the live one and this test's job is over.  `KeyError` is the shape the outcome happens
    to take -- the writer looks the atom up in the new structure's stereogenic set and it is absent --
    and what the criterion below is about is the WRITE, not the exception.

    THE ORACLE IS THE SUBJECT HERE AND NOT THE AUTHORITY: this behaviour is RECORDED, never adopted.
    Nothing in the core is derived from it; what it constrains is the acceptance criterion below.
    """
    verdicts = _verdicts()
    for module, rule_name in AFFECTED:
        outcome, detail = verdicts[f'{module}:{rule_name}:chiral']
        assert (outcome, detail) == ('raised', 'KeyError'), (module, rule_name, outcome, detail)


@mark.xfail(strict=True, reason='chython 3 acceptance criterion: no patcher implements this yet')
def test_a_patch_must_not_leave_a_parity_the_new_structure_cannot_own():
    """THE ACCEPTANCE CRITERION, in the only terms a container can be held to.

    A patch may destroy a stereocentre -- that is chemistry, and refusing the transformation would
    be worse.  What it may not do is leave the product carrying a label the product cannot
    interpret.  So the requirement is not "preserve the parity"; it is:

      * an atom that is no longer stereogenic in the PRODUCT carries no parity, and
      * an atom that is still stereogenic carries a parity RETRANSLATED into the product's
        neighbour order, never the old structure's,

    and the observable both reduce to is that the product can be written.  Stated that way it is
    checkable without agreeing in advance on which atoms survive as centres, which differs per
    template.

    Deliberately not asserted here: WHICH parity a surviving centre ends up with.  That is a
    retranslation question, it is `translate_stereo`'s in the core, and pinning a value here would
    duplicate that contract in a place that cannot see it.
    """
    verdicts = _verdicts()
    for module, rule_name in AFFECTED:
        outcome, detail = verdicts[f'{module}:{rule_name}:chiral']
        assert outcome == 'ok', (module, rule_name, detail)
