# -*- coding: utf-8 -*-
#
#  Copyright 2026 Ramil Nugmanov <nougmanoff@protonmail.com>
#  This file is part of chython.
#
#  chython is free software; you can redistribute it and/or modify
#  it under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Lesser General Public License for more details.
#
#  You should have received a copy of the GNU Lesser General Public License
#  along with this program; if not, see <https://www.gnu.org/licenses/>.
#
# Corpus-and-answers regression for arena version 4: the frozen buffers read, answer as frozen, and
# land their parities in SEG_PARITY.  The corpus and the answers are frozen -- never regenerated by a
# build under test.
from gzip import open as gzip_open
from pathlib import Path

from chython.core import MoleculeContainer
from chython.core._core import _parity_bytes

from .v4_fixtures import V4_ANSWERS, V4_SGROUP_STEREO_BYTES


def _records():
    with gzip_open(Path(__file__).parent / 'arena_v4_corpus.bin.gz', 'rb') as f:
        blob = f.read()
    at = 0
    while at < len(blob):
        n = int.from_bytes(blob[at:at + 4], 'little')
        at += 4
        yield blob[at:at + n]
        at += n


def test_the_frozen_corpus_states_version_four():
    versions = {raw[4] for raw in _records()}
    assert versions == {4}


def test_every_frozen_record_still_reads_and_answers():
    # Count is pinned separately: two records share a canonical SMILES key, so the key set alone
    # cannot detect a missing record.
    assert sum(1 for _ in _records()) == 8, 'the corpus has lost or gained a record'
    seen = set()
    for raw in _records():
        mol = MoleculeContainer.from_bytes(raw)
        key = str(mol)
        assert key in V4_ANSWERS, 'a frozen record no longer canonicalises to a frozen key: %s' % key
        want = V4_ANSWERS[key]
        assert {n: mol.parity_of(n) for n in mol.atom_numbers if mol.parity_of(n)} == want['parities']
        assert mol.wedges() == want['wedges']
        assert mol.stereo_groups() == want['stereo_groups']
        seen.add(key)
    assert seen == set(V4_ANSWERS), 'the corpus and the answer set have drifted apart'


def test_a_frozen_v4_buffer_lands_its_parities_in_the_segment():
    """Every stereocentre in the version-4 corpus survives ingest, and lands in SEG_PARITY.

    The flag bits are the only copy a version-4 buffer has, so an adoption that misses an atom loses a
    configuration no later pass can recover.  `test_every_frozen_record_still_reads_and_answers` pins
    the ANSWER; this pins the STORAGE, confirming the adoption captured every configured atom.

    The count is EXACT and counts RECORDS, not answer keys: six of the eight records state a parity,
    and the two that share a canonical key are both the alanine record.  A floor cannot notice one
    record dropping its parity while another gains one.
    """
    stated = 0
    for raw in _records():
        mol = MoleculeContainer.from_bytes(raw)
        want = V4_ANSWERS[str(mol)]['parities']
        if not want:
            continue
        stated += 1
        par = _parity_bytes(mol)
        assert par, '%s states a parity and carries no segment after ingest' % str(mol)
        numbers = list(mol.atom_numbers)
        for n, p in want.items():
            assert par[numbers.index(n)] == p, '%s: atom %d' % (str(mol), n)
    assert stated == 6, 'the corpus lost or gained a stereo-bearing record'


def test_an_sgroup_bearing_v4_buffer_keeps_its_sgroups_through_adoption():
    """Adoption replaces the buffer, so every OTHER persistent segment has to travel with it.

    A molecule with S-groups AND a stereocentre is the case that reaches every memcpy in
    `structure_with_parity` at once, and the only one that can catch a dropped arm.
    """
    mol = MoleculeContainer.from_bytes(V4_SGROUP_STEREO_BYTES)
    assert mol.sgroups, 'the S-groups did not survive adoption'
    assert any(mol.parity_of(n) for n in mol.atom_numbers), 'and neither did the stereocentre'
    assert _parity_bytes(mol), 'adopted, but into no segment'
    assert MoleculeContainer.from_bytes(mol.to_bytes()).sgroups == mol.sgroups
